# Based on https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - "3.4"

git:
    depth: 1

env:
    global:
        - OVERLAY_NAME='csmk'
    matrix:
        - PORTAGE_VER="2.3.0" REPOMAN_VER="2.3.0"

matrix:
    fast_finish: true

install:
    - .travis/install_portage.sh
    - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
    - export PORTAGE_CONFIGROOT="${PORTAGE_ROOT}" ROOT="${PORTAGE_ROOT}"

script:
    - repoman full -i -d

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
